### ISSUE TITLE
Request - ServerSide Only Setting

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [zlainsama/OfflineSkins#25]
So I would rather just post PNGs serverside and not have it installed clientside is that possible? That way no matter what all players will see the skins that are setup serverside.

**Comment by zlainsama** [comment]
Do you mean host player skin files by the game server and let the mod have an option to grab them from connected game server?

**Comment by P3rf3ctXZer0** [comment]
Um I would rather the players get skin info from server while it is running - so the server manager would recieve a png from the player and the server owner would place it in a folder serverside. This would eliminate any chance that the players on the server do not see the correct skins.

**Comment by zlainsama** [comment]
If without installing on client side, the mod will need to modify packets sent to clients about where the skin file is located (an URL), and you still need a web server to host those files (it is possible to start a web server from a mod, but you can't use the same port as the game server), because clients don't have the mod, a server side mod can't control exactly how clients getting skin files.
If with the mod installed on client side, it is possible to transfer skin files through the game server's network protocol, though it might affect the game server's networking performance.
And if you can host a web server, you are already capable of deciding what players will see on their clients, unless they changed the config.

**Comment by P3rf3ctXZer0** [comment]
So no fool proof way of controlling soley through serverside?

**Comment by zlainsama** [comment]
Yes, you will need a web server that is reachable from your clients and you have control over it.
Currently, the mod does not do anything when installed on server side, you can use a plugin framework like sponge or spigot with related plugins to control how information are sent to the client.

**Comment by P3rf3ctXZer0** [comment]
Question can you addsupport for username.png since so people cannot see other uuid?
