### ISSUE TITLE
1.9.4 - doesn't seem to work at all

### ISSUE THREAD

**Issue by c0rn3j** [zlainsama/OfflineSkins#4]
When I put the server in offline mode and logged in it, I expected it to pull my skin with the same nickname as the account, which it didn't, as I only had the Steve skin. Tried waiting for around 1 minute but nothing changed.

Tested against 1968 build of Forge

**Comment by BrisingrAerowing** [comment]
Same issue here. And since the Mojang skin servers seem to be glitched no custom skins show.

I tweeted Mojang about the skin server issues already. Their service status page says the skin servers are working, but they aren't.

Having dealt with web service back end systems before, I know all sorts of issues can occur that leave the service in an inconsistent state, making it necessary to restart the service to get it working again.

**Comment by zlainsama** [comment]
It worked fine here, but it's like 3 hours later.
I can't reproduce this. I think this is a misbehavior of Mojang's skin server (maybe reporting an OK status?).
Normally if Mojang's skin server fails, the mod will use skins from Crafatar.

**Comment by zlainsama** [comment]
A new version (1.9.4-v1a) has been released to fix this.
Please tell me if this is still happening.
