### ISSUE TITLE
[1.9.4] Missing heads from TAB menu

### ISSUE THREAD

**Issue by C0rn3j** [zlainsama/OfflineSkins#5]
I'm used to seeing the skin in the TAB menu, I assume this doesn't work for a server in offline state by default, could it be fixed? 
Current state: http://i.imgur.com/GawX1gR.png
What I mean: http://i.imgur.com/HPAqcna.png

**Comment by zlainsama** [comment]
I have checked the Minecraft code for that display.
It will render if the server is is a LAN server or the client has an encrypted connection to the server (which means the server and the client are in online state).
I find out that it uses uuid to identify players and display their heads on the menu, and in offline mode, uuid are not always synchronized between server and client (the client uses a uuid same as in online mode for it's current user even it is in offline mode, but server will send a different uuid used in offline mode because it doesn't know the uuid used in online mode), so they decided to render heads only in online mode, I think.

Yes, it can be fixed. But if I want to fix this problem, I will need to change that part of code to make it work which is too much effort for me at this time, maybe in the future.

**Comment by zlainsama** [comment]
a new version for 1.11 has been released to support tab menu player skins in offline mode.
it will be back ported to 1.10.

**Comment by C0rn3j** [comment]
Thank you so much for adding the only things that were missing in this mod!
