### ISSUE TITLE
OfflineSkins causes player heads to not function correctly

### ISSUE THREAD

**Issue by Mineralium** [zlainsama/OfflineSkins#80]
MC version: 1.21, mod version: v1
(but this bug is also present in earlier mc versions)

Basically, when someone gets their player head with command "/give @p minecraft:player_head[profile=USERNAME]", and later changes their skin (official launcher/website), the head is supposed to keep the old skin, but with this mod it doesn't and displays the new.

And I don't mean players who use this mod, this affects all player heads in any world and server. Of course this is purely client side, but this creates problems on servers where players can get their heads. This will happen even if I don't put any skins into the "skins" folder.

I think this mod should check the nbt/components of all player heads, and only if the name/uuid matches any name/uuid in the "skins" folder, should it change how the head looks in-game. Because right now it seems to just apply whatever the latest skin is on Mojang servers.

But if that is too complex, a config to just disable player head skin changes entirely would be good enough.

This was incredibly hard to describe, so I hope you understood what I mean.

**Comment by zlainsama** [comment]
Hmm, I know what you mean.
I thought player heads only display old/custom skins when they are told to do so by embedding fully realized profiles with textures through nbt/components in them.
The mod is resolving all profiles to official profiles if possible and then send skin request to respective servers, you should be able to disable all online servers through the config, doing so the mod still resolves profiles to official profiles but shouldn't grab latest skins from respective servers.
Another way to workaround this would be strip out all information regarding the owner of the player head so that the mod can't resolve their profiles, but this would require you to have access of server side things.
If you only need to use the mod for applying skins for some individuals, you can just disable all online servers through the config.
I will add a config option to disable the player head skin changes.

**Comment by zlainsama** [comment]
A version with the option to disable player head skin changes is out for 1.21.1, If you need jars for older Minecraft versions please let me know.

**Comment by Mineralium** [comment]
I have memory problems and forgot to check this. Thanks for making this change. The only older version I need is 1.21, but current jar already works fine without any edits. So.. not exactly needed, but you can probably add 1.21 to the list of supported versions on CurseForge.
